// packages/react/src/polee/hooks/use-event-listener.ts
import { useEffect } from "react";

import useIsClient from "./use-is-client";

const useEventListener = <K extends keyof WindowEventMap>(
  eventName: K,
  handler: (event: WindowEventMap[K]) => void,
  element?: EventTarget,
) => {
  const isClient = useIsClient();

  useEffect(() => {
    if (!isClient) return;

    const targetElement = element || window;
    const eventListener = (event: Event) => handler(event as WindowEventMap[K]);

    targetElement.addEventListener(eventName, eventListener);

    return () => {
      targetElement.removeEventListener(eventName, eventListener);
    };
  }, [eventName, handler, element, isClient]);
};

export default useEventListener;

// packages/solid/src/modal/hooks/use-event-listener.ts
import { type Accessor, createEffect, onCleanup, onMount } from "solid-js";

const useEventListener = <K extends keyof WindowEventMap>(
  eventType: K,
  handler: (event: WindowEventMap[K]) => void,
  target: Accessor<HTMLElement | EventTarget | null> | Window,
  options?: AddEventListenerOptions
) => {
  const eventListener = (event: Event) => handler(event as WindowEventMap[K]);

  createEffect(() => {
    if (target instanceof Window) {
      window.addEventListener(eventType, eventListener);

      onCleanup(() => window.removeEventListener(eventType, eventListener));
      return;
    }
    const container = target();
    if (!container) return;

    container.addEventListener(eventType, eventListener, options);

    onCleanup(() => {
      const container = target();
      if (!container) return;

      container.removeEventListener(eventType, eventListener, options);
    });
  });
};

export default useEventListener;
