// packages/ui/react/src/baek2back/utils/use-key-stroke.ts
import { useCallback } from "react";
import type { MaybeRef } from "./ref";
import { useEventListener } from "./use-event-listener";

export type Keys = string | string[];
export type KeyStrokeEventName = "keydown" | "keypress" | "keyup";
export type KeyStrokeOptions = {
  eventName?: KeyStrokeEventName;
  target?: MaybeRef<EventTarget>;
  code?: boolean;
  passive?: false;
};

export function useKeyStroke(
  keys: Keys,
  handler: (event: KeyboardEvent) => void,
  options: KeyStrokeOptions = {},
) {
  const {
    target = globalThis?.window,
    eventName = "keydown",
    passive = false,
    code = false,
  } = options;

  const listener = useCallback(
    (e: KeyboardEvent) => {
      const eventKey = code ? e.code : e.key;

      keys.includes(eventKey) && handler(e);
    },
    [code, handler, keys],
  );

  return useEventListener(target, eventName, listener, { passive });
}

// packages/solid/src/modal/hooks/use-key-stroke.ts
import type { Accessor } from 'solid-js';
import useEventListener from './use-event-listener';

export type Keys = string | string[];
export type KeyStrokeEventType = Extract<keyof WindowEventMap, 'keydown' | 'keypress' | 'keyup'>;
export type KeyStrokeOptions = {
  type?: KeyStrokeEventType;
  target?: Accessor<EventTarget>;
  code?: boolean;
};

export const useKeyStroke = <K extends KeyStrokeEventType>(
  keys: Keys,
  handler: (event: WindowEventMap[K]) => void,
  options?: KeyStrokeOptions
) => {
  const eventType = (options?.type ?? 'keydown') as K;
  const target = options?.target ?? globalThis.window;

  const listener = (e: WindowEventMap[K]) => {
    if (e instanceof KeyboardEvent) {
      const eventKey = options?.code ? e.code : e.key;

      if (keys.includes(eventKey)) {
        handler(e);
      }
    }
  };

  return useEventListener<K>(eventType, listener, target, { passive: false });
};
