// packages/react/src/polee/components/Modal/index.tsx
import type {
  CSSProperties,
  ComponentPropsWithoutRef,
  ForwardedRef,
  ReactNode,
  RefObject,
} from 'react';
import { forwardRef, useEffect, useId, useMemo, useRef } from 'react';

import { mergeRefs } from '@mash-ui/utils';
import { useClickOutside } from '../../hooks/use-click-outside';
import useEventListener from '../../hooks/use-event-listener';
import useModalTransition from '../../hooks/use-modal-transition';
import Portal from './Portal';

export interface ModalProps {
  children: ReactNode;
  onClose: VoidFunction;
  isOpen: boolean;
  shouldCloseOnDimClick?: boolean;
  initial?: CSSProperties;
  animate?: CSSProperties;
  exit?: CSSProperties;
  preventBackgroundScroll?: boolean;
  shouldCloseOnEsc?: boolean;
  mountNode?: RefObject<HTMLElement>;
  ariaLabelledby?: string;
  ariaDescribedby?: string;
}

const Backdrop = (props: ComponentPropsWithoutRef<'div'>) => {
  return (
    <div
      {...props}
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 9995,
        backgroundColor: 'rgb(0 0 0 / 0.4)',
        ...props.style,
      }}
    />
  );
};

const Modal = forwardRef((props: ModalProps, ref: ForwardedRef<HTMLDivElement>) => {
  const {
    children,
    onClose,
    isOpen,
    initial,
    animate,
    exit,
    ariaLabelledby,
    ariaDescribedby,
    mountNode,
    preventBackgroundScroll = true,
    shouldCloseOnDimClick = true,
    shouldCloseOnEsc = true,
  } = props;
  const portalId = useId();
  const modalRef = useRef<HTMLDivElement>(null);
  const { state, styles } = useModalTransition(isOpen, initial, animate, exit);

  useEventListener('keydown', (event: KeyboardEvent) => {
    if (shouldCloseOnEsc && event.key === 'Escape') {
      onClose();
    }
  });

  useEffect(() => {
    if (preventBackgroundScroll && state !== 'unmounted') {
      document.body.style.overflow = 'hidden';
    }

    return () => {
      if (preventBackgroundScroll) {
        document.body.style.overflow = '';
      }
    };
  }, [preventBackgroundScroll, state]);

  const modalStyle = useMemo(() => {
    const styles: CSSProperties = {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 9996,
    };
    return styles;
  }, []);

  useClickOutside(
    modalRef,
    () => {
      if (shouldCloseOnDimClick) {
        onClose();
      }
    },
    { event: 'pointerdown' }
  );

  if (!isOpen && state === 'unmounted') {
    return null;
  }

  return (
    <Portal id={portalId} containerRef={mountNode}>
      <Backdrop />

      <div
        ref={mergeRefs([modalRef, ref])}
        role="dialog"
        aria-modal="true"
        tabIndex={-1}
        aria-labelledby={ariaLabelledby}
        aria-describedby={ariaDescribedby}
        style={{ ...modalStyle, ...styles }}
      >
        {children}
      </div>
    </Portal>
  );
});

Modal.displayName = 'Modal';

export default Modal;

// packages/solid/src/modal/Modal.tsx
import type { Accessor, JSX, ParentComponent } from 'solid-js';
import { Show, createSignal, mergeProps } from 'solid-js';
import { Portal } from 'solid-js/web';

import Backdrop from './Backdrop';
import injectAnimation from './hooks/inject-animation';
import useClickOutside from './hooks/use-click-outside';
import { useKeyStroke } from './hooks/use-key-stroke';
import usePreventBodyScroll from './hooks/use-prevent-body-scroll';

interface ModalProps {
  isOpen: Accessor<boolean>;
  onClose: VoidFunction;
  initial?: JSX.CSSProperties;
  animate?: JSX.CSSProperties;
  exit?: JSX.CSSProperties;
  dimStyle?: JSX.CSSProperties;
  ariaLabelledby?: string;
  ariaDescribedby?: string;
  preventBackgroundScroll?: boolean;
  shouldCloseOnDimClick?: boolean;
  shouldCloseOnESC?: boolean;
}

const Modal: ParentComponent<ModalProps> = (defaultProps) => {
  const props = mergeProps(
    {
      shouldCloseOnDimClick: true,
      shouldCloseOnESC: true,
      preventBackgroundScroll: true,
    },
    defaultProps
  );

  const [modalRef, setModalRef] = createSignal<HTMLDivElement | null>(null);

  const startExitAnimation = injectAnimation(modalRef, props.initial, props.animate, props.exit);

  const closeModal = () => {
    startExitAnimation();
    setTimeout(() => {
      props.onClose();
    }, 300);
  };

  useKeyStroke(['Escape'], () => {
    if (props.isOpen() && props.shouldCloseOnESC) {
      closeModal();
    }
  });

  const onCloseDimClick = () => {
    if (props.isOpen() && props.shouldCloseOnDimClick) {
      closeModal();
    }
  };
  useClickOutside(modalRef, onCloseDimClick, 'pointerdown');

  usePreventBodyScroll({ isOpen: props.isOpen });

  return (
    <Portal>
      <Show when={props.isOpen()}>
        <>
          <Backdrop style={props.dimStyle} />

          <div
            ref={setModalRef}
            role="dialog"
            aria-modal="true"
            tabIndex={-1}
            aria-labelledby={props.ariaLabelledby}
            aria-describedby={props.ariaDescribedby}
            style={{
              position: 'fixed',
              top: '50%',
              left: '50%',
              transform: 'translate(-50%, -50%)',
              'z-index': 9999,
              transition: 'all 0.3s',
            }}
          >
            {props.children}
          </div>
        </>
      </Show>
    </Portal>
  );
};

export default Modal;
