// packages/solid/src/modal/hooks/use-click-outside.ts
import type { Accessor } from 'solid-js';
import useEventListener from './use-event-listener';

export type ClickOutsideEvents = Extract<
  keyof WindowEventMap,
  'mousedown' | 'mouseup' | 'touchstart' | 'touchend' | 'pointerdown' | 'pointerup'
>;

const useClickOutside = <K extends ClickOutsideEvents>(
  target: Accessor<HTMLElement | null>,
  handler: (event: WindowEventMap[K]) => void,
  event?: K
) => {
  const eventType = event ?? ('pointerdown' as K);

  const listener = (event: WindowEventMap[K]) => {
    const container = target();
    if (!container) return;

    if (container === event.target || event.composedPath().includes(container)) return;

    handler(event);
  };

  useEventListener<K>(eventType, listener, () => document, { passive: true });
};

export default useClickOutside;

// packages/react/src/polee/hooks/use-click-outside.ts
import { useCallback } from "react";
import { unRef, type MaybeRef } from "./ref";
import useEventListener from "./use-event-listener";

export type ClickOutsideEvents = Pick<
  WindowEventMap,
  | "mousedown"
  | "mouseup"
  | "touchstart"
  | "touchend"
  | "pointerdown"
  | "pointerup"
>;
export interface ClickOutsideOptions<E extends keyof ClickOutsideEvents> {
  event?: E;
}

export function useClickOutside<
  E extends keyof ClickOutsideEvents = "pointerdown",
>(
  target: MaybeRef<Element | null | undefined>,
  handler: (evt: ClickOutsideEvents[E]) => void,
  options: ClickOutsideOptions<E> = {},
) {
  const { event = "pointerdown" } = options;

  const listener = useCallback(
    (event: ClickOutsideEvents[E]) => {
      const el = unRef(target);
      if (!el) return;

      if (el === event.target || event.composedPath().includes(el)) return;

      handler(event);
    },
    [handler, target],
  );

  return useEventListener(globalThis?.window, event, listener, {
    passive: true,
  });
}
