// packages/solid/src/modal/Modal.tsx
import type { Accessor, JSX, ParentComponent } from 'solid-js';
import { Show, createSignal, mergeProps } from 'solid-js';
import { Portal } from 'solid-js/web';

import Backdrop from './Backdrop';
import injectAnimation from './hooks/inject-animation';
import useClickOutside from './hooks/use-click-outside';
import { useKeyStroke } from './hooks/use-key-stroke';
import usePreventBodyScroll from './hooks/use-prevent-body-scroll';

interface ModalProps {
  isOpen: Accessor<boolean>;
  onClose: VoidFunction;
  initial?: JSX.CSSProperties;
  animate?: JSX.CSSProperties;
  exit?: JSX.CSSProperties;
  dimStyle?: JSX.CSSProperties;
  ariaLabelledby?: string;
  ariaDescribedby?: string;
  preventBackgroundScroll?: boolean;
  shouldCloseOnDimClick?: boolean;
  shouldCloseOnESC?: boolean;
}

const Modal: ParentComponent<ModalProps> = (defaultProps) => {
  const props = mergeProps(
    {
      shouldCloseOnDimClick: true,
      shouldCloseOnESC: true,
      preventBackgroundScroll: true,
    },
    defaultProps
  );

  const [modalRef, setModalRef] = createSignal<HTMLDivElement | null>(null);

  const startExitAnimation = injectAnimation(modalRef, props.initial, props.animate, props.exit);

  const closeModal = () => {
    startExitAnimation();
    setTimeout(() => {
      props.onClose();
    }, 300);
  };

  useKeyStroke(['Escape'], () => {
    if (props.isOpen() && props.shouldCloseOnESC) {
      closeModal();
    }
  });

  const onCloseDimClick = () => {
    if (props.isOpen() && props.shouldCloseOnDimClick) {
      closeModal();
    }
  };
  useClickOutside(modalRef, onCloseDimClick, 'pointerdown');

  usePreventBodyScroll({ isOpen: props.isOpen });

  return (
    <Portal>
      <Show when={props.isOpen()}>
        <>
          <Backdrop style={props.dimStyle} />

          <div
            ref={setModalRef}
            role="dialog"
            aria-modal="true"
            tabIndex={-1}
            aria-labelledby={props.ariaLabelledby}
            aria-describedby={props.ariaDescribedby}
            style={{
              position: 'fixed',
              top: '50%',
              left: '50%',
              transform: 'translate(-50%, -50%)',
              'z-index': 9999,
              transition: 'all 0.3s',
            }}
          >
            {props.children}
          </div>
        </>
      </Show>
    </Portal>
  );
};

export default Modal;

// packages/react/src/baek2back/components/modal/modal.tsx
import { mergeRefs } from "@mash-ui/utils";
import { forwardRef, useRef, type ComponentPropsWithoutRef } from "react";
import { useClickOutside } from "../../utils/use-click-outside";
import { useControllableState } from "../../utils/use-controllable-state";
import { useKeyStroke } from "../../utils/use-key-stroke";
import { useLockBodyScroll } from "../../utils/use-lock-body-scroll";
import { Portal } from "../portal";

const Backdrop = (props: ComponentPropsWithoutRef<"div">) => {
  return (
    <div
      {...props}
      style={{
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: Number.MAX_SAFE_INTEGER - 1,
        backgroundColor: "rgb(0 0 0 / 0.4)",
        ...props.style,
      }}
    />
  );
};

export interface ModalProps {
  isOpen?: boolean;
  onOpenChange?: (value: boolean) => void;
}

export const Modal = forwardRef<HTMLDivElement, ModalProps>((props, ref) => {
  const modalRef = useRef<HTMLDivElement>(null);

  const [isOpen, setIsOpen] = useControllableState({
    value: props.isOpen,
    onChange: props.onOpenChange,
    defaultValue: false,
  });

  useLockBodyScroll({ locked: isOpen });

  useClickOutside(
    modalRef,
    () => {
      setIsOpen(false);
    },
    { event: "mousedown" }
  );

  useKeyStroke(["Escape"], (event) => {
    setIsOpen(false);
  });

  if (!isOpen) return null;

  return (
    <Portal>
      <Backdrop />
      <div
        role="dialog"
        ref={mergeRefs([ref, modalRef])}
        aria-modal="true"
        aria-labelledby="header"
        aria-describedby="body"
        style={{
          position: "fixed",
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
          zIndex: Number.MAX_SAFE_INTEGER,
          backgroundColor: "white",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <span id="header">Modal header</span>
        <span id="body">Modal body</span>
        <button
          onClick={() => {
            setIsOpen(false);
          }}
        >
          Close
        </button>
      </div>
    </Portal>
  );
});
